name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime:
          - win-x64
          - linux-x64
          - osx-arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Publish
        run: |
          dotnet publish ./PassphraseGenerator.csproj \
            -c Release \
            -r ${{ matrix.runtime }} \
            -o publish/${{ matrix.runtime }}

      - name: Zip files
        run: |
          cd publish/${{ matrix.runtime }}

          if [[ "${{ matrix.runtime }}" == win-* ]]; then
            zip -r ../../sph-${{ matrix.runtime }}.zip .
          else
            tar -czf ../../sph-${{ matrix.runtime }}.tar.gz .
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sph-*
